before_install:
  - sudo add-apt-repository -y ppa:gladky-anton/gnuplot
  - sudo apt-get update -q
  - sudo apt-get install -y gnuplot
  # Fails because gnuplot is too old there.
  #- sudo apt-get update -qq
  #- sudo apt-get install gnuplot-x11
script:
  - gnuplot --version
  - make zip
deploy:
  provider: releases
  api_key: 'TODO'
  file: 'gnuplot-examples.zip'
  skip_cleanup: true
  on:
    tags: true
